---
- name: Install required packages
  yum:
    name:
      - curl
      - policycoreutils-python
      - openssh-server
    state: latest

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: Enable HTTP+HTTPS access
  firewalld:
    # This is how we use a variable
    service: "{{ item }}"
    permanent: yes
    state: enabled
  # The module will be run for each item
  with_items:
    - http
    - https

# - name: Reload firewalld
sudo systemctl reload firewalld

# - name: Install postfix
sudo yum install postfix

# - name: Enable and start postfix
sudo systemctl enable postfix
sudo systemctl start postfix

# - name: Download GitLab package script
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash
#   TIP: Use the get_url module to download the script.rpm.sh

# - name: Execute GitLab package script
sudo EXTERNAL_URL="http://gitlab.local" yum install -y gitlab-ee
#   TIP: Use the script module to run the script.rpm.sh

- name: Install GitLab
  yum:
    name: gitlab-ee
  environment:
    EXTERNAL_URL: http://gitlab.local
